<a href="https://colab.research.google.com/github/satya2436/Autonomous-Robot-ESP32/blob/master/NUMPY.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [0]:
import numpy as np
from numpy import array
#numeric python=NUMPY
lst=[1,2,3]
print(lst)
temp=np.array(lst)
print(temp)
print(temp[0])
xl=array(lst)
print(xl)
"""You could perform mathematical operations like additions, subtraction, division and multiplication on an array. The syntax is the array name followed by the operation (+.-,*,/) followed by the operand
"""
print(xl+3)

#Shape of Array - to get the dimention of the array
print(xl.shape)
#type of the element in the array
print(xl.dtype)


### 2 dimension
c = np.array([(1,2,3),
              (4,5,6)])
print(c.shape)

### 3 dimension
d = np.array([
    [[1, 2,3],
        [4, 5, 6]],
    [[7, 8,9],
        [10, 11, 12]]
])
print(d.shape)

"""
You can create a matrix full of zeroes or ones using np.zeros and np.one commands respectively. It can be used when you initialized the weights during the first iteration in TensorFlow and other statistic tasks.
"""
#Numpy Zero
#numpy.zeros(shape, dtype=float, order='C')
#Numpy Once
#numpy.ones(shape, dtype=float, order='C')
"""
Shape: is the shape of the array

Dtype: is the datatype. It is optional. The default value is float64

Order: Default is C which is an essential row style.

"""
print(np.zeros((4,4),int))
print(np.ones((4,5),int))
"""
Reshape Data
In some occasions, you need to reshape the data from wide to long. You can use the reshape function for this. The syntax is

numpy.reshape(a, newShape, order='C')
Here,

a: Array that you want to reshape

newShape: The new desires shape

Order: Default is C which is an essential row style.
"""
np.reshape(d,(3,4))
print(d.flatten())


print("********************")

"""
With hstack you can appened data horizontally. This is a very convinient function in Numpy. Lets study it with an example:

## Horitzontal Stack
"""
f = np.array([1,2,3])
g = np.array([4,5,6])
print('Horizontal Append:', np.hstack((f, g)))

"""
With vstack you can appened data vertically. Lets study it with an example:
## Vertical Stack
"""

f = np.array([1,2,3])
g = np.array([4,5,6])

print('Vertical Append:', np.vstack((f, g)))


'''
Generate Random Numbers
To generate random numbers for Gaussian distribution use

numpy.random.normal(loc, scale, size)

Here

Loc: the mean. The center of distribution
scale: standard deviation.
Size: number of returns
'''

## Generate random nmber from normal distribution
normal_array = np.random.normal(5, 0.5, 10)
print(normal_array)	
'''

'''

A = np.matrix(np.ones((4,4)))
print(A)
np.array(A)[2]=2
print(A)
#matrix is immutable so we can use asarray to change its value
np.asarray(A)[2]=2
print(A)

'''
Whay is Arrange?
Sometimes, you want to create values that are evenly spaced within a defined interval. For instance, you want to create values from 1 to 10; you can use numpy.arange() function

Syntax:

numpy.arange(start, stop,step) 


Start: Start of interval
Stop: End of interval
Step: Spacing between values. Default step is 1

'''
d=np.arange(1, 11)
print(d)
d=np.arange(1, 14, 4)
print(d)

'''
Linspace
Linspace gives evenly spaced samples.

Syntax:

numpy.linspace(start, stop, num, endpoint)


Here,

Start: Starting value of the sequence
Stop: End value of the sequence
Num: Number of samples to generate. Default is 50
Endpoint: If True (default), stop is the last value. If False, stop value is not included.
'''
d= np.linspace(1.0, 5.0, num=10)
print(d)
d=np.linspace(1.0, 5.0, num=5, endpoint=False)
print(d)

'''
LogSpace
LogSpace returns even spaced numbers on a log scale. Logspace has the same parameters as np.linspace.

Syntax:

numpy.logspace(start, stop, num, endpoint)
'''
d=np.logspace(3.0, 4.0, num=4)
print(d)
x = np.array([1,2,3], dtype=np.complex128)
print(x.itemsize)

#indexing and slicing is also possible in numpy array

'''
NumPy has quite a few useful statistical functions for finding minimum, maximum, percentile standard deviation and variance, etc from the given elements in the array. The functions are explained as follows −

Statistical function
Numpy is equipped with the robust statistical function as listed below

Function	           Numpy
Min	                np.min()
Max	                np.max()
Mean	              np.mean()
Median	            np.median()
Standard deviation	np.std()
'''

normal_array = np.random.normal(5, 0.5, 10)
print(normal_array)
### Min 
print(np.min(normal_array))

### Max 
print(np.max(normal_array))

### Mean 
print(np.mean(normal_array))

### Median
print(np.median(normal_array))

### Sd
print(np.std(normal_array))

'''
Dot Product
Numpy is powerful library for matrices computation. For instance, you can compute the dot product with np.dot

Syntax

numpy.dot(x, y, out=None)
Here,

x,y: Input arrays. x and y both should be 1-D or 2-D for the function to work

out: This is the output argument.For 1-D array scalar is returned. Other wise ndarray
'''

## Linear algebra
### Dot product: product of two arrays
f = np.array([1,2])
g = np.array([4,5])
### 1*4+2*5
print(np.dot(f, g))

'''
Matrix Multiplication
The Numpu matmul() function is used to return the matrix product of 2 arrays. Here is how it works

1) 2-D arrays, it returns normal product

2) Dimensions > 2, the product is treated as a stack of matrix

3) 1-D array is first promoted to a matrix, and then the product is calculated

numpy.matmul(x, y, out=None)
Here,

x,y: Input arrays. scalars not allowed

out: This is optional parameter. Usually output is stored in ndarray

Example:

In the same way, you can compute matrices multiplication with np.matmul
'''

### Matmul: matruc product of two arrays
h = [[1,2],[3,4]] 
i = [[5,6],[7,8]] 
### 1*5+2*7 = 19
np.matmul(h, i)
"""
Determinant
Last but not least, if you need to compute the determinant, you can use np.linalg.det(). Note that numpy takes care of the dimension.
"""
print(np.linalg.det(h))


[1, 2, 3]
[1 2 3]
1
[1 2 3]
[4 5 6]
(3,)
int64
(2, 3)
(2, 2, 3)
[[0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]]
[[1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]]
[ 1  2  3  4  5  6  7  8  9 10 11 12]
********************
Horizontal Append: [1 2 3 4 5 6]
Vertical Append: [[1 2 3]
 [4 5 6]]
[4.78735226 4.92656927 4.92777079 5.22846412 5.29255927 5.44296593
 5.01274271 4.71286551 5.24738567 6.00586691]
[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]
[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]
[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [2. 2. 2. 2.]
 [1. 1. 1. 1.]]
[ 1  2  3  4  5  6  7  8  9 10]
[ 1  5  9 13]
[1.         1.44444444 1.88888889 2.33333333 2.77777778 3.22222222
 3.66666667 4.11111111 4.55555556 5.        ]
[1.  1.8 2.6 3.4 4.2]
[ 1000.          2154.43469003  4641.58883361 10000.        ]
16
[4.88500471 4.70932381 4.81364901 5.45095086 4.76932273 4.78880662
 4.36275225 4.99105297 5.63824263 4.82521508]
4.362752246276024
5.638242625392218
4.923432064688641
4